# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TestLoginFoursquare' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestLoginFoursquare
  pod 'FSOAuth', '1.2.1'

end
