# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FacebookLogin' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FacebookLogin
  pod 'FBSDKCoreKit', '4.14.0'
  pod 'FBSDKLoginKit', '4.14.0'
  pod 'FBSDKShareKit', '4.14.0'

end
